name: yolo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  image_picker: ^0.8.7
  path_provider: ^2.0.0
  archive: ^3.0.0
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  file: ^7.0.1
  platform: ^3.1.6
  ultralytics_yolo:
    path: packages/ultralytics_yolo-0.1.42
  system_monitor:
    path: packages/system_monitor

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  injectable_generator: ^2.9.1
  mockito: ^5.6.1
  bloc_test: ^10.0.0
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^6.0.0
  # fake_async: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
